#!/bin/bash
echo "GMPM System Status Report"
echo "========================"
echo "Date: $(date)"
echo ""
echo "Components:"
echo "- Router: $([ -f ~/app/src/Router.php ] && echo "✓" || echo "✗")"
echo "- Controllers: $(ls ~/app/src/Controllers/*.php 2>/dev/null | wc -l) files"
echo "- Middleware: $(ls ~/app/src/Middleware/*.php 2>/dev/null | wc -l) files"
echo "- Views: $(find ~/app/resources/views -name "*.php" 2>/dev/null | wc -l) files"
echo "- Config: $(ls ~/app/config/*.php 2>/dev/null | wc -l) files"
echo ""
echo "FastRoute: $(cd ~/app && composer show nikic/fast-route 2>/dev/null | grep -o "v[0-9.]*" || echo "Not installed")"
echo ""
echo "PHP Version: $(php -v | head -1)"
echo "Session Path: $(php -r 'echo session_save_path();')"
echo ""
echo "Recent Errors:"
tail -5 ~/app/error_log 2>/dev/null || echo "No app errors"
